# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7fd6034ffa0b6160efbd874bbfed27d39108a85eefc0f378e7b924f70f35ad57cf6a352333d991752876fd9b2c9729d326040e71d57c8499c6089112edd3e0

test:
  secret_key_base: a7603b01b1dabd297421643df9c48be8e1c1a2f8285a968aff9e98ab66026a94cb73574c1aef2ff320f4639227ac5b7da544525d3c3c26cc47479e0cb2119f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: a7603b01b1dabd297421643df9c48be8e1c1a2f8285a968aff9e98ab66026a94cb73574c1aef2ff320f4639227ac5b7da544525d3c3c26cc47479e0cb2119f32
